mv 1942.zip 'Shooter' # 1942 (Revision B) []
mv 1943.zip 'Shooter' # 1943: The Battle of Midway (Euro) []
mv 19xx.zip 'Shooter' # 19XX: The War Against Destiny (Euro 960104) []
mv 2020bb.zip 'Sports' # 2020 Super Baseball (set 1) []
mv 64street.zip 'Fighter' # 64th. Street - A Detective Story (World) []
mv 88games.zip 'Sports' # '88 Games []
mv agallet.zip 'Shooter' # Air Gallet (Europe) []
mv airbustr.zip 'Shooter' # Air Buster: Trouble Specialty Raid Unit (World) []
mv alexkidd.zip 'Platform' # Alex Kidd: The Lost Stars (set 2, unprotected) []
mv aliens.zip 'Platform' # Aliens (World set 1) []
mv aliensyn.zip 'Maze' # Alien Syndrome (set 4, System 16B, unprotected) []
mv alpham2.zip 'Shooter' # Alpha Mission II / ASO II - Last Guardian (NGM-007 ~ NGH-007) []
mv alpine.zip 'Sports' # Alpine Ski (set 1) []
mv altbeast.zip 'Platform' # Altered Beast (set 8) (8751 317-0078) []
mv androdun.zip 'Shooter' # Andro Dunos (NGM-049 ~ NGH-049) []
mv anteater.zip 'Maze' # Anteater []
mv aof3.zip 'Vs Fighter' # Art of Fighting 3 - The Path of the Warrior / Art of Fighting - Ryuuko no Ken Gaiden []
mv aquajack.zip 'Shooter' # Aqua Jack (World) []
mv arabfgt.zip 'Fighter' # Arabian Fight (World) []
mv arabian.zip 'Platform' # Arabian []
mv archrivl.zip 'Sports' # Arch Rivals (rev 4.0 6/29/89) []
mv armwar.zip 'Platform' # Armored Warriors (Euro 941024) []
mv assaultp.zip 'Shooter' # Assault Plus (Japan) []
mv astdelux.zip 'Shooter' # Asteroids Deluxe (rev 3) []
mv asterix.zip 'Fighter' # Asterix (ver EAD) []
mv astinvad.zip 'Shooter' # Astro Invader []
mv astorm.zip 'Platform' # Alien Storm (World, 2 Players) (FD1094 317-0154) []
mv astrob.zip 'Shooter' # Astro Blaster (version 3) []
mv asurabld.zip 'Vs Fighter' # Asura Blade - Sword of Dynasty (Japan) []
mv atetrisa.zip 'Puzzle' # Tetris (set 2) []
mv athena.zip 'Platform' # Athena []
mv avengers.zip 'Fighter' # Avengers (US set 1) []
mv avsp.zip 'Fighter' # Alien vs. Predator (Euro 940520) []
mv avspirit.zip 'Platform' # Avenging Spirit []
mv baddudes.zip 'Platform' # Bad Dudes vs. Dragonninja (US revision 1) []
mv bagman.zip 'Platform' # Bagman []
mv balcube.zip 'Ball & Paddle' # Bal Cube []
mv bangball.zip 'Puzzle' # Bang Bang Ball (v1.05) []
mv bangbead.zip 'Sports' # Bang Bead []
mv batcir.zip 'Fighter' # Battle Circuit (Euro 970319) []
mv batrider.zip 'Shooter' # Armed Police Batrider (Europe) (Fri Feb 13 1998) []
mv batsugun.zip 'Shooter' # Batsugun []
mv battlega.zip 'Shooter' # Battle Garegga (Europe / USA / Japan / Asia) (Sat Feb 3 1996) []
mv battlera.zip 'Shooter' # Battle Rangers (World) []
mv bayroute.zip 'Platform' # Bay Route (set 3, World) (FD1094 317-0116) []
mv bbakraid.zip 'Shooter' # Battle Bakraid - Unlimited Version (USA) (Tue Jun 8 1999) []
mv bbmanw.zip 'Maze' # Bomber Man World / New Dyna Blaster - Global Quest []
mv bchopper.zip 'Shooter' # Battle Chopper (World) []
mv benberob.zip 'Platform' # Ben Bero Beh (Japan) []
mv berzerk.zip 'Maze' # Berzerk (revision RC31A) []
mv bigbang.zip 'Shooter' # Big Bang (9th Nov. 1993) []
mv bigkarnk.zip 'Platform' # Big Karnak []
mv biomtoy.zip 'Platform' # Biomechanical Toy (Ver. 1.0.1885) []
mv bionicc.zip 'Platform' # Bionic Commando (Euro) []
mv bjourney.zip 'Platform' # Blue's Journey / Raguy (ALM-001 ~ ALH-001) []
mv bjtwin.zip 'Platform' # Bombjack Twin (set 1) []
mv blazeon.zip 'Shooter' # Blaze On (World) []
mv blazstar.zip 'Shooter' # Blazing Star []
mv blitz.zip 'Sports' # NFL Blitz (ver 1.21, Dec 5 1987) []
mv blkheart.zip 'Shooter' # Black Heart []
mv blktiger.zip 'Platform' # Black Tiger []
mv blockhl.zip 'Puzzle' # Block Hole []
mv blockout.zip 'Puzzle' # Block Out (set 1) []
mv bloodbro.zip 'Shooter' # Blood Bros. (World?) []
mv blswhstl.zip 'Shooter' # Bells & Whistles (World, version L) []
mv bmaster.zip 'Fighter' # Blade Master (World) []
mv bnzabros.zip 'Platform' # Bonanza Bros (US, Floppy DS3-5000-07d? Based) []
mv bombjack.zip 'Platform' # Bomb Jack (set 1) []
mv bonkadv.zip 'Platform' # B.C. Kid / Bonk's Adventure / Kyukyoku!! PC Genjin []
mv boogwing.zip 'Shooter' # Boogie Wings (Euro v1.5, 92.12.07) []
mv bosco.zip 'Shooter' # Bosconian - Star Destroyer (new version) []
mv brapboys.zip 'Fighter' # B.Rap Boys (World) []
mv breakrev.zip 'Vs Fighter' # Breakers Revenge []
mv brvblade.zip 'Shooter' # Brave Blade (World) []
mv bssoccer.zip 'Sports' # Back Street Soccer (KRB-0031 PCB) []
mv bstars2.zip 'Sports' # Baseball Stars 2 []
mv btime.zip 'Platform' # Burger Time (Data East set 1) []
mv btoads.zip 'Fighter' # Battletoads []
mv bubblem.zip 'Platform' # Bubble Memories: The Story Of Bubble Bobble III (Ver 2.4O 1996/02/15) []
mv bubbles.zip 'Maze' # Bubbles []
mv bublbob2.zip 'Platform' # Bubble Bobble II (Ver 2.6O 1994/12/16) [Slow]
mv bublbobl.zip 'Platform' # Bubble Bobble (Japan, Ver 0.1) []
mv bubsymph.zip 'Platform' # Bubble Symphony (Ver 2.5J 1994/10/05) []
mv buckrog.zip 'Shooter' # Buck Rogers: Planet of Zoom []
mv bucky.zip 'Shooter' # Bucky O'Hare (ver EAB) []
mv burningf.zip 'Fighter' # Burning Fight (NGM-018 ~ NGH-018) []
mv bwidow.zip 'Shooter' # Black Widow []
mv bzone.zip 'Shooter' # Battle Zone (rev 2) []
mv cabal.zip 'Shooter' # Cabal (World, Joystick) []
mv cadash.zip 'Platform' # Cadash (World) []
mv calibr50.zip 'Shooter' # Caliber 50 (Ver. 1.01) []
mv captaven.zip 'Fighter' # Captain America and The Avengers (Asia Rev 1.4) []
mv captcomm.zip 'Fighter' # Captain Commando (World 911202) []
mv carnival.zip 'Shooter' # Carnival (upright, AY8912 music) []
mv cawing.zip 'Shooter' # Carrier Air Wing (World 901012) []
mv cbaj.zip 'Sports' # Cool Boarders Arcade Jam (Export) [Slow]
mv cbasebal.zip 'Sports' # Capcom Baseball (Japan) []
mv centiped.zip 'Shooter' # Centipede (revision 4) []
mv chplft.zip 'Shooter' # Choplifter (8751 315-5151) []
mv chukatai.zip 'Shooter' # Chuka Taisen (World) (P0-028-A PCB) []
mv circusc.zip 'Platform' # Circus Charlie (level select, set 1) []
mv cloak.zip 'Shooter' # Cloak & Dagger (rev 5) []
mv clshroad.zip 'Driving' # Clash-Road []
mv cninja.zip 'Platform' # Caveman Ninja (World ver 4) []
mv cobracom.zip 'Shooter' # Cobra-Command (World/US revision 5) []
mv columns.zip 'Puzzle' # Columns (World) []
mv commando.zip 'Shooter' # Commando (World) []
mv congo.zip 'Platform' # Congo Bongo (Rev C, 2 board stack) []
mv contra.zip 'Platform' # Contra (US / Asia, set 1) []
mv cosmogng.zip 'Shooter' # Cosmo Gang the Video (US) []
mv cotton.zip 'Shooter' # Cotton (set 4, World) (FD1094 317-0181a) []
mv cotton2.zip 'Shooter' # Cotton 2 (JUET 970902 V1.000) []
mv cottonbm.zip 'Shooter' # Cotton Boomerang (JUET 980709 V1.000) []
mv crimec.zip 'Platform' # Crime City (World) []
mv crimfght.zip 'Fighter' # Crime Fighters (World 2 players) []
mv crkdown.zip 'Maze' # Crack Down (World, Floppy Based, FD1094 317-0058-04c) []
mv crospang.zip 'Puzzle' # Cross Pang []
mv crush.zip 'Maze' # Crush Roller (set 1) []
mv crysking.zip 'Fighter' # The Crystal of Kings []
mv csclub.zip 'Sports' # Capcom Sports Club (Euro 971017) []
mv cshift.zip 'Puzzle' # Chicken Shift []
mv ctribe.zip 'Fighter' # The Combatribes (US, rev 2, set 1) []
mv cupfinal.zip 'Sports' # Taito Cup Finals (Ver 1.0O 1993/02/28) []
mv cybattlr.zip 'Shooter' # Cybattler []
mv cyberbal.zip 'Sports' # Cyberball (rev 4) []
mv cyberlip.zip 'Platform' # Cyber-Lip (NGM-010) []
mv cybotsu.zip 'Vs Fighter' # Cyberbots: Fullmetal Madness (USA 950424) []
mv cyvern.zip 'Shooter' # Cyvern - The Dragon Weapons (US) []
mv daraku.zip 'Vs Fighter' # The Fallen Angels (World) / Daraku Tenshi - The Fallen Angels (Japan) []
mv darius.zip 'Shooter' # Darius (World, rev 2) []
mv dariusg.zip 'Shooter' # Darius Gaiden - Silver Hawk (Ver 2.5O 1994/09/19) [Slow]
mv dbreed.zip 'Shooter' # Dragon Breed (World, M81 hardware) []
mv ddonpach.zip 'Shooter' # DoDonPachi (International, Master Ver. 97/02/05) []
mv ddp2.zip 'Shooter' # DoDonPachi II - Bee Storm (World, ver. 102) []
mv ddragon.zip 'Fighter' # Double Dragon (Japan) []
mv ddragon2.zip 'Fighter' # Double Dragon II - The Revenge (World) []
mv ddsom.zip 'Fighter' # Dungeons & Dragons: Shadow over Mystara (Euro 960619) []
mv ddtod.zip 'Fighter' # Dungeons & Dragons: Tower of Doom (Euro 940412) []
mv deadconx.zip 'Shooter' # Dead Connection (World) []
mv defender.zip 'Shooter' # Defender (Red label) []
mv demonwld.zip 'Platform' # Demon's World / Horror Story (set 1) []
mv denjinmk.zip 'Fighter' # Denjin Makai (set 1) []
mv desertwr.zip 'Shooter' # Desert War / Wangan Sensou (ver 1.0) []
mv dharma.zip 'Maze' # Dharma Doujou []
mv digdug.zip 'Maze' # Dig Dug (rev 2) []
mv digdug2.zip 'Maze' # Dig Dug II (New Ver.) []
mv dimahoo.zip 'Shooter' # Dimahoo (Euro 000121) []
mv dino.zip 'Fighter' # Cadillacs and Dinosaurs (World 930201) []
mv dkong.zip 'Platform' # Donkey Kong (US set 1) []
mv dkong3.zip 'Platform' # Donkey Kong 3 (US) []
mv dkongjr.zip 'Platform' # Donkey Kong Junior (US set F-2) []
mv doapp.zip 'Vs Fighter' # Dead Or Alive ++ (Japan/USA/Export) [Slow]
mv docastle.zip 'Platform' # Mr. Do's Castle (set 1) []
mv dogyuun.zip 'Shooter' # Dogyuun []
mv dommy.zip 'Maze' # Dommy []
mv dondokod.zip 'Platform' # Don Doko Don (World) []
mv dowild.zip 'Platform' # Mr. Do's Wild Ride []
mv dragnblz.zip 'Shooter' # Dragon Blaze []
mv drgnbstr.zip 'Platform' # Dragon Buster []
mv driftout.zip 'Driving' # Drift Out (Europe) []
mv drmario.zip 'Puzzle' # Vs. Dr. Mario []
mv drmicro.zip 'Platform' # Dr. Micro []
mv drtoppel.zip 'Shooter' # Dr. Toppel's Adventure (World) []
mv dsaber.zip 'Shooter' # Dragon Saber (World, DO2) []
mv dspirit.zip 'Shooter' # Dragon Spirit (new version (DS3)) []
mv dynagear.zip 'Platform' # Dyna Gear []
mv dynwar.zip 'Fighter' # Dynasty Wars (USA, B-Board 89624B-?) []
mv ecofghtr.zip 'Shooter' # Eco Fighters (World 931203) []
mv edf.zip 'Shooter' # E.D.F. : Earth Defense Force (set 1) []
mv edrandy.zip 'Fighter' # The Cliffhanger - Edward Randy (World ver 3) []
mv ehrgeiz.zip 'Vs Fighter' # Ehrgeiz (World, EG2/VER.A) [Slow]
mv eightman.zip 'Platform' # Eight Man (NGM-025 ~ NGH-025) []
mv elevator.zip 'Platform' # Elevator Action (BA3, 4 PCB version, 1.1) []
mv elvactr.zip 'Platform' # Elevator Action Returns (Ver 2.2O 1995/02/20) []
mv emeralda.zip 'Puzzle' # Emeraldia (World) [Slow]
mv enforce.zip 'Shooter' # Enforce (World) []
mv eprom.zip 'Maze' # Escape from the Planet of the Robot Monsters (set 1) []
mv esprade.zip 'Shooter' # ESP Ra.De. (International, Ver. 98/04/22) []
mv eswat.zip 'Platform' # E-Swat - Cyber Police (set 4, World) (FD1094 317-0130) []
mv excitebk.zip 'Driving' # Vs. Excitebike (set EB4-3 E) []
mv exedexes.zip 'Shooter' # Exed Exes []
mv extdwnhl.zip 'Sports' # Extreme Downhill (v1.5) []
mv eyes.zip 'Maze' # Eyes (US set 1) []
mv fantjour.zip 'Shooter' # Fantastic Journey (ver EAA) []
mv fantzone.zip 'Shooter' # Fantasy Zone (Rev A, unprotected) []
mv fatfury3.zip 'Vs Fighter' # Fatal Fury 3 - Road to the Final Victory / Garou Densetsu 3 - Haruka-naru Tatakai (NGM-069 ~ NGH-069) []
mv fbfrenzy.zip 'Sports' # Football Frenzy (NGM-034 ~ NGH-034) []
mv feversos.zip 'Shooter' # Fever SOS (International, Ver. 98/09/25) []
mv ffight.zip 'Fighter' # Final Fight (World, set 1) []
mv fgtlayer.zip 'Vs Fighter' # Fighting Layer (Japan, FTL1/VER.A) [Slow]
mv flamegun.zip 'Shooter' # Flame Gunner (Export) [Slow]
mv flipshot.zip 'Sports' # Battle Flip Shot []
mv footchmp.zip 'Sports' # Football Champ / Euro Football Champ (World) []
mv frogger.zip 'Maze' # Frogger []
mv fshark.zip 'Shooter' # Flying Shark (World) []
mv fstarfrc.zip 'Shooter' # Final Star Force (US) []
mv funkyjet.zip 'Platform' # Funky Jet (World, rev 1) []
mv ga2.zip 'Fighter' # Golden Axe: The Revenge of Death Adder (World, Rev B) [Slow]
mv gaia.zip 'Fighter' # Gaia Crusaders []
mv gaiapols.zip 'Fighter' # Gaiapolis (ver EAF) []
mv galaga.zip 'Shooter' # Galaga (Namco rev. B) []
mv galaga88.zip 'Shooter' # Galaga '88 []
mv galaxian.zip 'Shooter' # Galaxian (Namco set 1) []
mv gametngk.zip 'Shooter' # The Game Paradise - Master of Shooting! / Game Tengoku - The Game Paradise (ver 1.0) []
mv ganryu.zip 'Platform' # Ganryu / Musashi Ganryuki []
mv garou.zip 'Vs Fighter' # Garou - Mark of the Wolves (NGM-2530) []
mv gaunt22p.zip 'Maze' # Gauntlet II (2 Players, rev 2) []
mv gauntdl.zip 'Maze' # Gauntlet Dark Legacy (version DL 2.52) [Slow]
mv gauntleg.zip 'Maze' # Gauntlet Legends (version 1.6) [Slow]
mv gauntlet.zip 'Maze' # Gauntlet (rev 14) []
mv gaxeduel.zip 'Vs Fighter' # Golden Axe - The Duel (JUETL 950117 V1.000) [Slow]
mv gberet.zip 'Platform' # Green Beret []
mv gbusters.zip 'Shooter' # Gang Busters (set 1) []
mv gemini.zip 'Shooter' # Gemini Wing (World) []
mv gforce2.zip 'Shooter' # Galaxy Force 2 []
mv ghostb.zip 'Shooter' # The Real Ghostbusters (US 2 Players, revision 2) []
mv ghostlop.zip 'Puzzle' # Ghostlop (prototype) []
mv ghouls.zip 'Platform' # Ghouls'n Ghosts (World) []
mv gigawing.zip 'Shooter' # Giga Wing (USA 990222) []
mv gnbarich.zip 'Ball & Paddle' # Gunbarich []
mv gng.zip 'Platform' # Ghosts'n Goblins (World? set 1) []
mv goldnaxe.zip 'Fighter' # Golden Axe (set 6, US) (8751 317-123A) []
mv gorf.zip 'Shooter' # Gorf []
mv gradius.zip 'Shooter' # Gradius (Japan, ROM version) []
mv gradius2.zip 'Shooter' # Gradius II - GOFER no Yabou (Japan New Ver.) []
mv gratia.zip 'Shooter' # Gratia - Second Earth (ver 1.0, 92047-01 version) []
mv grdians.zip 'Fighter' # Guardians / Denjin Makai II (P-FG01-1 PCB) []
mv grdius3e.zip 'Shooter' # Gradius III (World ?) []
mv growl.zip 'Fighter' # Growl (World, Rev 1) []
mv gtmr.zip 'Driving' # 1000 Miglia: Great 1000 Miles Rally (Taiwan 94/07/18) []
mv gunbird.zip 'Shooter' # Gunbird (World) []
mv gunbird2.zip 'Shooter' # Gunbird 2 (set 1) []
mv gundamex.zip 'Vs Fighter' # Mobile Suit Gundam EX Revue []
mv gundhara.zip 'Shooter' # Gundhara []
mv gunforc2.zip 'Platform' # Gun Force II (US) []
mv gunforce.zip 'Platform' # Gunforce - Battle Fire Engulfed Terror Island (World) []
mv gunfront.zip 'Shooter' # Gun & Frontier (World) []
mv gunlock.zip 'Shooter' # Gunlock (Ver 2.3O 1994/01/20) []
mv gunsmoke.zip 'Shooter' # Gun.Smoke (World, 851115) []
mv guwange.zip 'Shooter' # Guwange (Japan, Master Ver. 99/06/24) []
mv gwar.zip 'Shooter' # Guerrilla War (US) []
mv gyruss.zip 'Shooter' # Gyruss []
mv hattrick.zip 'Sports' # Hat Trick []
mv hbarrel.zip 'Shooter' # Heavy Barrel (World) []
mv hcastle.zip 'Platform' # Haunted Castle (version M) []
mv hellfire.zip 'Shooter' # Hellfire (2P set) []
mv hharry.zip 'Platform' # Hammerin' Harry (World, M81 hardware) []
mv hook.zip 'Fighter' # Hook (World) []
mv htchctch.zip 'Puzzle' # Hatch Catch []
mv hvysmsh.zip 'Sports' # Heavy Smash (Europe version -2) []
mv hyperath.zip 'Sports' # Hyper Athlete (GV021 Japan 1.00) [Slow]
mv hyperspt.zip 'Sports' # Hyper Sports []
mv hyprduel.zip 'Shooter' # Hyper Duel (Japan set 1) []
mv hypsptsp.zip 'Sports' # Hyper Sports Special (Japan) []
mv ikari.zip 'Shooter' # Ikari Warriors (US JAMMA) []
mv ikari3.zip 'Shooter' # Ikari III - The Rescue (World version 1, 8-Way Joystick) []
mv imgfight.zip 'Shooter' # Image Fight (World) []
mv indytemp.zip 'Maze' # Indiana Jones and the Temple of Doom (set 1) []
mv inthunt.zip 'Shooter' # In The Hunt (World) []
mv invaders.zip 'Shooter' # Space Invaders / Space Invaders M []
mv invadpt2.zip 'Shooter' # Space Invaders Part II (Taito, bigger ROMs) []
mv irrmaze.zip 'Maze' # The Irritating Maze / Ultra Denryu Iraira Bou []
mv jjack.zip 'Platform' # Jumping Jack []
mv jjsquawk.zip 'Platform' # J. J. Squawkers []
mv joemacr.zip 'Platform' # Joe & Mac Returns (World, Version 1.1, 1994.05.27) []
mv jojo.zip 'Vs Fighter' # JoJo's Venture (Euro 990128) []
mv jojoba.zip 'Vs Fighter' # JoJo's Bizarre Adventure (Euro 990927) []
mv journey.zip 'Maze' # Journey []
mv joust.zip 'Platform' # Joust (Green label) []
mv joust2.zip 'Platform' # Joust 2 - Survival of the Fittest (revision 2) []
mv joyjoy.zip 'Puzzle' # Puzzled / Joy Joy Kid (NGM-021 ~ NGH-021) []
mv jrpacman.zip 'Maze' # Jr. Pac-Man (11/9/83) []
mv junglek.zip 'Platform' # Jungle King (Japan) []
mv jungler.zip 'Maze' # Jungler []
mv junofrst.zip 'Shooter' # Juno First []
mv kangaroo.zip 'Platform' # Kangaroo []
mv karianx.zip 'Puzzle' # Karian Cross (Rev. 1.0) []
mv karnov.zip 'Platform' # Karnov (US, rev 6) []
mv kbash.zip 'Vs Fighter' # Knuckle Bash []
mv kchamp.zip 'Vs Fighter' # Karate Champ (US) []
mv kicker.zip 'Platform' # Kicker []
mv kidniki.zip 'Platform' # Kid Niki - Radical Ninja (World) []
mv kingdmgp.zip 'Shooter' # Kingdom Grandprix []
mv kingofb.zip 'Sports' # King of Boxer (World) []
mv kinst.zip 'Vs Fighter' # Killer Instinct [Slow]
mv kizuna.zip 'Vs Fighter' # Kizuna Encounter - Super Tag Battle / Fu'un Super Tag Battle []
mv klax.zip 'Puzzle' # Klax (version 6) []
mv knights.zip 'Fighter' # Knights of the Round (World 911127) []
mv kod.zip 'Fighter' # The King of Dragons (World 910805) []
mv kof2000.zip 'Vs Fighter' # The King of Fighters 2000 (NGM-2570 ~ NGH-2570) []
mv kof96.zip 'Vs Fighter' # The King of Fighters '96 (NGM-214) []
mv kof98.zip 'Vs Fighter' # The King of Fighters '98 - The Slugfest / King of Fighters '98 - Dream Match Never Ends (NGM-2420) []
mv kotm2.zip 'Fighter' # King of the Monsters 2 - The Next Thing (NGM-039 ~ NGH-039) []
mv kov.zip 'Fighter' # Knights of Valour / Sanguo Zhan Ji / Sangoku Senki (ver. 117, Hong Kong) []
mv kov2.zip 'Fighter' # Knights of Valour 2 / Sanguo Zhan Ji 2 / Sangoku Senki 2 (ver. 107, 102, 100HK) []
mv krull.zip 'Shooter' # Krull []
mv kungfum.zip 'Fighter' # Kung-Fu Master (World) []
mv ladybug.zip 'Maze' # Lady Bug []
mv landmakr.zip 'Puzzle' # Land Maker (Ver 2.02O 1998/06/02) [Slow]
mv lastblad.zip 'Vs Fighter' # The Last Blade / Bakumatsu Roman - Gekka no Kenshi (NGM-2340) []
mv lastbld2.zip 'Vs Fighter' # The Last Blade 2 / Bakumatsu Roman - Dai Ni Maku Gekka no Kenshi (NGM-2430 ~ NGH-2430) []
mv lbowling.zip 'Sports' # League Bowling (NGM-019 ~ NGH-019) []
mv ldrun.zip 'Platform' # Lode Runner (set 1) []
mv ldrun2.zip 'Platform' # Lode Runner II - The Bungeling Strikes Back []
mv ldrun3.zip 'Platform' # Lode Runner III - The Golden Labyrinth []
mv ldrun4.zip 'Platform' # Lode Runner IV - Teikoku Karano Dasshutsu (Japan) []
mv lethalth.zip 'Shooter' # Lethal Thunder (World) []
mv liblrabl.zip 'Puzzle' # Libble Rabble []
mv lightbr.zip 'Maze' # Light Bringer (Ver 2.2O 1994/04/08) []
mv liquidk.zip 'Platform' # Liquid Kids (World) []
mv liquidku.zip 'Platform' # Liquid Kids (US) []
mv locomotn.zip 'Puzzle' # Loco-Motion []
mv loderndf.zip 'Platform' # Lode Runner - The Dig Fight (ver. B) []
mv lresort.zip 'Shooter' # Last Resort []
mv lwings.zip 'Shooter' # Legendary Wings (US set 1) []
mv macea.zip 'Vs Fighter' # Mace: The Dark Age (HDD 1.0a) [CHD]
mv machbrkr.zip 'Sports' # Mach Breakers (World, MB2) []
mv macross.zip 'Shooter' # Super Spacefortress Macross / Chou-Jikuu Yousai Macross []
mv macross2.zip 'Shooter' # Super Spacefortress Macross II / Chou-Jikuu Yousai Macross II []
mv macrossp.zip 'Shooter' # Macross Plus []
mv madgear.zip 'Driving' # Mad Gear (US) []
mv magdrop2.zip 'Puzzle' # Magical Drop II []
mv magdrop3.zip 'Puzzle' # Magical Drop III []
mv maglord.zip 'Platform' # Magician Lord (NGM-005) []
mv mappy.zip 'Platform' # Mappy (US) []
mv mario.zip 'Platform' # Mario Bros. (US, Revision G) []
mv marvland.zip 'Platform' # Marvel Land (US, prototype?) []
mv matrim.zip 'Vs Fighter' # Matrimelee / Shin Gouketsuji Ichizoku Toukon (NGM-2660 ~ NGH-2660) []
mv mazinger.zip 'Shooter' # Mazinger Z (World) []
mv mcatadv.zip 'Platform' # Magical Cat Adventure []
mv megaman2.zip 'Vs Fighter' # Mega Man 2: The Power Fighters (USA 960708) []
mv mercs.zip 'Shooter' # Mercs (World 900302) []
mv metalb.zip 'Shooter' # Metal Black (World) []
mv metamrph.zip 'Fighter' # Metamorphic Force (ver EAA) []
mv metlhawk.zip 'Shooter' # Metal Hawk (Rev C) []
mv metmqstr.zip 'Vs Fighter' # Metamoqester (International) []
mv midres.zip 'Platform' # Midnight Resistance (World) []
mv miexchng.zip 'Puzzle' # Money Puzzle Exchanger / Money Idol Exchanger []
mv milliped.zip 'Shooter' # Millipede []
mv mk2.zip 'Vs Fighter' # Mortal Kombat II (rev L3.1) [Slow]
mv mmatrix.zip 'Shooter' # Mars Matrix: Hyper Solid Shooting (USA 000412) []
mv mmaze.zip 'Maze' # Marchen Maze (Japan) []
mv momoko.zip 'Platform' # Momoko 120% (Japanese text) []
mv monsterb.zip 'Platform' # Monster Bash []
mv moo.zip 'Platform' # Wild West C.O.W.-Boys of Moo Mesa (ver EA) []
mv mooncrst.zip 'Shooter' # Moon Cresta (Nichibutsu) []
mv mosaicf2.zip 'Puzzle' # Mosaic (F2 System) []
mv motos.zip 'Puzzle' # Motos []
mv mp_gaxe2.zip 'Fighter' # Golden Axe II (Mega Play) (Rev B) []
mv mp_soni2.zip 'Platform' # Sonic The Hedgehog 2 (Mega Play) []
mv mp_sonic.zip 'Platform' # Sonic The Hedgehog (Mega Play) []
mv mp_sor2.zip 'Fighter' # Streets of Rage II (Mega Play) []
mv mpatrol.zip 'Shooter' # Moon Patrol []
mv mrdo.zip 'Maze' # Mr. Do! []
mv mrdrillr.zip 'Puzzle' # Mr. Driller (US, DRI3/VER.A2) [Slow]
mv mslug.zip 'Platform' # Metal Slug - Super Vehicle-001 []
mv mslug2.zip 'Platform' # Metal Slug 2 - Super Vehicle-001/II (NGM-2410 ~ NGH-2410) []
mv mslug3.zip 'Platform' # Metal Slug 3 (NGM-2560) []
mv mslug4.zip 'Platform' # Metal Slug 4 (NGM-2630) []
mv mslug5.zip 'Platform' # Metal Slug 5 (NGM-2680) []
mv mslugx.zip 'Platform' # Metal Slug X - Super Vehicle-001 (NGM-2500 ~ NGH-2500) []
mv mspacman.zip 'Maze' # Ms. Pac-Man []
mv mspacmnf.zip 'Maze' # Ms. Pac-Man (speedup hack) []
mv msword.zip 'Platform' # Magic Sword: Heroic Fantasy (World 900725) []
mv mtlchamp.zip 'Vs Fighter' # Martial Champion (ver EAB) []
mv mtrap.zip 'Maze' # Mouse Trap (version 5) []
mv mtwins.zip 'Platform' # Mega Twins (World 900619) []
mv mutnat.zip 'Fighter' # Mutation Nation (NGM-014 ~ NGH-014) []
mv mwalk.zip 'Platform' # Michael Jackson's Moonwalker (World) (FD1094/8751 317-0159) []
mv mysticri.zip 'Shooter' # Mystic Riders (World) []
mv mystwarr.zip 'Fighter' # Mystic Warriors (ver EAA) []
mv nagano98.zip 'Sports' # Nagano Winter Olympics '98 (GX720 EAA) [Slow]
mv nam1975.zip 'Shooter' # NAM-1975 (NGM-001 ~ NGH-001) []
mv narc.zip 'Platform' # Narc (rev 7.00) []
mv nbahangt.zip 'Sports' # NBA Hangtime (ver L1.3 10/10/96) []
mv nbajam.zip 'Sports' # NBA Jam (rev 3.01 4/07/93) []
mv nbbatman.zip 'Fighter' # Ninja Baseball Bat Man (World) []
mv ncommand.zip 'Shooter' # Ninja Commando []
mv nemesis.zip 'Shooter' # Nemesis (ROM version) []
mv nemo.zip 'Platform' # Nemo (World 901130) []
mv neobombe.zip 'Maze' # Neo Bomberman []
mv neodrift.zip 'Driving' # Neo Drift Out - New Technology []
mv neomrdo.zip 'Maze' # Neo Mr. Do! []
mv nibbler.zip 'Maze' # Nibbler (rev 9, set 1) []
mv nightstr.zip 'Shooter' # Night Striker (World) []
mv ninjak.zip 'Fighter' # The Ninja Kids (World) []
mv nitd.zip 'Platform' # Nightmare in the Dark []
mv nitrobal.zip 'Shooter' # Nitro Ball (World, set 1) []
mv nost.zip 'Shooter' # Nostradamus []
mv nslasher.zip 'Fighter' # Night Slashers (Korea Rev 1.3, DE-0397-0 PCB) []
mv nspirit.zip 'Fighter' # Ninja Spirit (World) []
mv nwarr.zip 'Vs Fighter' # Night Warriors: Darkstalkers' Revenge (Euro 950316) []
mv offroadt.zip 'Driving' # Ironman Ivan Stewart's Super Off-Road Track-Pak []
mv ohmygod.zip 'Puzzle' # Oh My God! (Japan) []
mv openice.zip 'Sports' # 2 On 2 Open Ice Challenge (rev 1.21) []
mv ordyne.zip 'Shooter' # Ordyne (World) []
mv orlegend.zip 'Fighter' # Oriental Legend / Xiyou Shi E Chuan (ver. 126) []
mv oscar.zip 'Platform' # Psycho-Nics Oscar (World revision 0) []
mv osman.zip 'Platform' # Osman (World) []
mv outfxies.zip 'Platform' # The Outfoxies (World, OU2) [Slow]
mv outzone.zip 'Shooter' # Out Zone []
mv overtop.zip 'Driving' # Over Top []
mv p47.zip 'Shooter' # P-47 - The Phantom Fighter (World) []
mv p47aces.zip 'Shooter' # P-47 Aces (ver 1.1) []
mv pacland.zip 'Platform' # Pac-Land (World) []
mv pacman.zip 'Maze' # Pac-Man (Midway) []
mv pacmanf.zip 'Maze' # Pac-Man (Midway, speedup hack) []
mv pandoras.zip 'Platform' # Pandora's Palace []
mv pang.zip 'Shooter' # Pang (World) []
mv pang3.zip 'Shooter' # Pang! 3 (Euro 950601) []
mv panic.zip 'Platform' # Space Panic (version E) []
mv panicbom.zip 'Puzzle' # Panic Bomber []
mv panicstr.zip 'Puzzle' # Panic Street (Japan) []
mv parodius.zip 'Shooter' # Parodius DA! (World, set 1) []
mv pblbeach.zip 'Sports' # Pebble Beach - The Great Shot (JUE 950913 V0.990) []
mv pbobble2.zip 'Puzzle' # Puzzle Bobble 2 (Ver 2.3O 1995/07/31) [Slow]
mv pbobble4.zip 'Puzzle' # Puzzle Bobble 4 (Ver 2.04O 1997/12/19) []
mv pc_mtoid.zip 'Platform' # Metroid (PlayChoice-10) []
mv penbros.zip 'Platform' # Penguin Brothers (Japan) []
mv pengo.zip 'Maze' # Pengo (set 1 rev C, encrypted) []
mv pepper2.zip 'Maze' # Pepper II (version 8) []
mv perfrman.zip 'Maze' # Performan (Japan) []
mv pgoal.zip 'Sports' # Pleasure Goal / Futsal - 5 on 5 Mini Soccer (NGM-219) []
mv phelios.zip 'Shooter' # Phelios []
mv phoenix.zip 'Shooter' # Phoenix (Amstar, set 1) []
mv pigout.zip 'Platform' # Pig Out: Dine Like a Swine! (rev 2?) []
mv pigskin.zip 'Sports' # Pigskin 621AD (rev 1.1K 8/01/90) []
mv pipedrm.zip 'Puzzle' # Pipe Dream (World) []
mv pirates.zip 'Shooter' # Pirates (set 1) []
mv pisces.zip 'Shooter' # Pisces []
mv pitfall2.zip 'Platform' # Pitfall II (315-5093) []
mv pktgaldx.zip 'Sports' # Pocket Gal Deluxe (Euro v3.00) []
mv pkunwar.zip 'Sports' # Penguin-Kun Wars (US) []
mv plotting.zip 'Puzzle' # Plotting (World set 1) []
mv plsmaswd.zip 'Vs Fighter' # Plasma Sword: Nightmare of Bilstein (USA 980316) [Slow]
mv plusalph.zip 'Shooter' # Plus Alpha []
mv pnyaa.zip 'Puzzle' # Pochi and Nyaa (Ver 2.02) []
mv pooyan.zip 'Shooter' # Pooyan []
mv popeye.zip 'Platform' # Popeye (revision D) []
mv popnpop.zip 'Puzzle' # Pop'n Pop (Ver 2.07O 1998/02/09) []
mv pow.zip 'Fighter' # P.O.W. - Prisoners of War (US version 1) []
mv prehisle.zip 'Shooter' # Prehistoric Isle in 1930 (World) []
mv primrage.zip 'Vs Fighter' # Primal Rage (version 2.3) [Slow]
mv progear.zip 'Shooter' # Progear (USA 010117) []
mv psychic5.zip 'Platform' # Psychic 5 (World) []
mv puchicar.zip 'Ball & Paddle' # Puchi Carat (Ver 2.02O 1997/10/29) [Slow]
mv puckman.zip 'Maze' # Puck Man (Japan set 1) []
mv pulirula.zip 'Fighter' # PuLiRuLa (World) []
mv pulstar.zip 'Shooter' # Pulstar []
mv punchout.zip 'Sports' # Punch-Out!! (Rev B) []
mv punisher.zip 'Fighter' # The Punisher (World 930422) []
mv punkshot.zip 'Sports' # Punk Shot (US 4 Players) []
mv pururun.zip 'Puzzle' # Pururun []
mv puyopuy2.zip 'Puzzle' # Puyo Puyo 2 (Japan) []
mv puzzledp.zip 'Puzzle' # Puzzle De Pon! []
mv puzzli.zip 'Puzzle' # Puzzli (revision B) []
mv puzzloop.zip 'Puzzle' # Puzz Loop (Europe, v0.94) []
mv puzznic.zip 'Maze' # Puzznic (World) []
mv pwrgoal.zip 'Sports' # Taito Power Goal (Ver 2.5O 1994/11/03) []
mv qbert.zip 'Platform' # Q*bert (US set 1) []
mv qix.zip 'Puzzle' # Qix (Rev 2) []
mv rabbit.zip 'Vs Fighter' # Rabbit (Asia 3/6) []
mv raiden.zip 'Shooter' # Raiden (set 1) []
mv raiden2.zip 'Shooter' # Raiden II (US, set 1) []
mv raiders5.zip 'Maze' # Raiders5 []
mv rainbow.zip 'Platform' # Rainbow Islands []
mv rallybik.zip 'Driving' # Rally Bike / Dash Yarou []
mv rallyx.zip 'Maze' # Rally X (32k Ver.?) []
mv rambo3.zip 'Shooter' # Rambo III (Europe) []
mv rampage.zip 'Platform' # Rampage (Rev 3, 8/27/86) []
mv ramprt2p.zip 'Shooter' # Rampart (Joystick) []
mv rastan.zip 'Platform' # Rastan (World Rev 1) []
mv raystorm.zip 'Shooter' # Ray Storm (Ver 2.06A) [Slow]
mv rbff2.zip 'Vs Fighter' # Real Bout Fatal Fury 2 - The Newcomers / Real Bout Garou Densetsu 2 - The Newcomers (NGM-2400) []
mv rbtapper.zip 'Platform' # Tapper (Root Beer) []
mv rdft2.zip 'Shooter' # Raiden Fighters 2 - Operation Hell Dive (Germany) []
mv recalh.zip 'Platform' # Recalhorn (Ver 1.42J 1994/5/11, prototype) []
mv rfjet.zip 'Shooter' # Raiden Fighters Jet (Germany) []
mv ringdest.zip 'Sports' # Ring of Destruction: Slammasters II (Euro 940902) []
mv ringking.zip 'Sports' # Ring King (US set 1) []
mv riotcity.zip 'Fighter' # Riot City (Japan) []
mv ripoff.zip 'Shooter' # Rip Off []
mv rmpgwt.zip 'Platform' # Rampage: World Tour (rev 1.3) []
mv roboarmy.zip 'Fighter' # Robo Army []
mv robocop.zip 'Platform' # Robocop (World revision 4) []
mv robocop2.zip 'Fighter' # Robocop 2 (Euro/Asia v0.10) []
mv robotron.zip 'Shooter' # Robotron: 2084 (Solid Blue label) []
mv rocnrope.zip 'Platform' # Roc'n Rope []
mv rodland.zip 'Platform' # Rod-Land (World, set 1) []
mv rohga.zip 'Platform' # Rohga Armor Force (Asia/Europe v5.0) []
mv rohgau.zip 'Platform' # Rohga Armor Force (US v1.0) []
mv rollerg.zip 'Sports' # Rollergames (US) []
mv rotd.zip 'Vs Fighter' # Rage of the Dragons (NGM-2640?) []
mv rsgun.zip 'Shooter' # Radiant Silvergun (JUET 980523 V1.000) [Slow]
mv rthun2.zip 'Platform' # Rolling Thunder 2 []
mv rthunder.zip 'Platform' # Rolling Thunder (rev 3) []
mv rtype.zip 'Shooter' # R-Type (World) []
mv rtype2.zip 'Shooter' # R-Type II (World) []
mv rtypeleo.zip 'Shooter' # R-Type Leo (World) []
mv rungun.zip 'Sports' # Run and Gun (ver EAA 1993 10.8) []
mv rushhero.zip 'Sports' # Rushing Heroes (ver UAB) []
mv rvschool.zip 'Vs Fighter' # Rival Schools: United By Fate (Euro 971117) [Slow]
mv rygar.zip 'Platform' # Rygar (US set 1) []
mv ryujin.zip 'Shooter' # Ryu Jin (Japan, ET910000B PCB) []
mv s1945ii.zip 'Shooter' # Strikers 1945 II []
mv s1945iii.zip 'Shooter' # Strikers 1945 III (World) / Strikers 1999 (Japan) []
mv sabotenb.zip 'Platform' # Saboten Bombers (set 1) []
mv sailormn.zip 'Fighter' # Pretty Soldier Sailor Moon (Ver. 95/03/22B, Europe) []
mv salamand.zip 'Shooter' # Salamander (version D) []
mv salmndr2.zip 'Shooter' # Salamander 2 (ver JAA) []
mv samsh5sp.zip 'Vs Fighter' # Samurai Shodown V Special / Samurai Spirits Zero Special (NGM-2720) []
mv samsho2.zip 'Vs Fighter' # Samurai Shodown II / Shin Samurai Spirits - Haohmaru Jigokuhen (NGM-063 ~ NGH-063) []
mv samsho3.zip 'Vs Fighter' # Samurai Shodown III / Samurai Spirits - Zankurou Musouken (NGM-087) []
mv samuraia.zip 'Shooter' # Samurai Aces (World) []
mv sbagman.zip 'Platform' # Super Bagman (version 5) []
mv scobra.zip 'Shooter' # Super Cobra []
mv scontra.zip 'Platform' # Super Contra (set 1) []
mv scramble.zip 'Shooter' # Scramble []
mv scregg.zip 'Maze' # Scrambled Egg []
mv sdungeon.zip 'Shooter' # Space Dungeon []
mv searchar.zip 'Shooter' # SAR - Search And Rescue (World) []
mv seawolf.zip 'Shooter' # Sea Wolf (set 1) []
mv seawolf2.zip 'Shooter' # Sea Wolf II []
mv secretag.zip 'Platform' # Secret Agent (World revision 3) []
mv sengoku.zip 'Fighter' # Sengoku / Sengoku Denshou (NGM-017 ~ NGH-017) []
mv sengoku2.zip 'Fighter' # Sengoku 2 / Sengoku Denshou 2 []
mv sengoku3.zip 'Fighter' # Sengoku 3 / Sengoku Densho 2001 (set 1) []
mv sexyparo.zip 'Shooter' # Sexy Parodius (ver JAA) []
mv sf2ce.zip 'Vs Fighter' # Street Fighter II': Champion Edition (World 920513) []
mv sfa2.zip 'Vs Fighter' # Street Fighter Alpha 2 (Euro 960229) []
mv sfa3.zip 'Vs Fighter' # Street Fighter Alpha 3 (Euro 980904) []
mv sfex2p.zip 'Vs Fighter' # Street Fighter EX2 Plus (Euro 990611) [Slow]
mv sfexa.zip 'Vs Fighter' # Street Fighter EX (Asia 961219) [Slow]
mv sfiii3.zip 'Vs Fighter' # Street Fighter III 3rd Strike: Fight for the Future (Euro 990608) []
mv sgemf.zip 'Vs Fighter' # Super Gem Fighter Mini Mix (USA 970904) []
mv shadfrce.zip 'Fighter' # Shadow Force (World, Version 3) []
mv shadoww.zip 'Fighter' # Shadow Warriors (World, set 1) []
mv sharrier.zip 'Shooter' # Space Harrier (Rev A, 8751 315-5163A) []
mv shdancer.zip 'Platform' # Shadow Dancer (World) []
mv shienryu.zip 'Shooter' # Shienryu (JUET 961226 V1.000) []
mv shimpact.zip 'Sports' # Super High Impact (rev LA1 09/30/91) []
mv shinobi.zip 'Platform' # Shinobi (set 6, System 16A) (unprotected) []
mv shocktr2.zip 'Shooter' # Shock Troopers - 2nd Squad []
mv shocktro.zip 'Shooter' # Shock Troopers (set 1) []
mv shollow.zip 'Shooter' # Satan's Hollow (set 1) []
mv sidearms.zip 'Shooter' # Side Arms - Hyper Dyne (World, 861129) []
mv silentd.zip 'Fighter' # Silent Dragon (World) []
mv silkroad.zip 'Fighter' # The Legend of Silkroad []
mv simpbowl.zip 'Sports' # Simpsons Bowling (GQ829 UAA) [Slow]
mv simpsn2p.zip 'Fighter' # The Simpsons (2 Players World, set 1) []
mv skykid.zip 'Shooter' # Sky Kid (new version) []
mv slammast.zip 'Sports' # Saturday Night Slam Masters (World 930713) []
mv slapshot.zip 'Sports' # Slap Shot (Ver 3.0 O) []
mv slyspy.zip 'Platform' # Sly Spy (US revision 4) []
mv smashtv.zip 'Shooter' # Smash T.V. (rev 8.00) []
mv snakepit.zip 'Fighter' # Snake Pit []
mv snowbro2.zip 'Platform' # Snow Bros. 2 - With New Elves / Otenki Paradise (Hanafram) []
mv snowbros.zip 'Platform' # Snow Bros. - Nick & Tom (set 1) []
mv socbrawl.zip 'Sports' # Soccer Brawl (NGM-031) []
mv sokyugrt.zip 'Shooter' # Soukyugurentai / Terra Diver (JUET 960821 V1.000) [Slow]
mv solarq.zip 'Shooter' # Solar Quest (rev 10 8 81) []
mv soldivid.zip 'Shooter' # Sol Divide - The Sword Of Darkness []
mv solomon.zip 'Puzzle' # Solomon's Key (US) []
mv sonicwi2.zip 'Shooter' # Aero Fighters 2 / Sonic Wings 2 []
mv sonson.zip 'Platform' # Son Son []
mv soulclbr.zip 'Vs Fighter' # Soul Calibur (World, SOC14/VER.C) [Slow]
mv spacduel.zip 'Shooter' # Space Duel (version 2) []
mv spacedx.zip 'Shooter' # Space Invaders DX (US, v2.1) []
mv spacefb.zip 'Shooter' # Space Firebird (rev. 04-u) []
mv spang.zip 'Shooter' # Super Pang (World 900914) []
mv spdodgeb.zip 'Sports' # Super Dodge Ball (US) []
mv speedspn.zip 'Sports' # Speed Spin []
mv spelunkr.zip 'Platform' # Spelunker []
mv spf2t.zip 'Puzzle' # Super Puzzle Fighter II Turbo (Euro 960529) []
mv spidman.zip 'Platform' # Spider-Man: The Videogame (World) []
mv spinmast.zip 'Platform' # Spin Master / Miracle Adventure []
mv splatter.zip 'Fighter' # Splatter House (World, new version (SH3)) []
mv sqix.zip 'Puzzle' # Super Qix (World/Japan, V1.2) []
mv srumbler.zip 'Shooter' # The Speed Rumbler (set 1) []
mv ssf2t.zip 'Vs Fighter' # Super Street Fighter II Turbo (World 940223) []
mv ssi.zip 'Shooter' # Super Space Invaders '91 (World, Rev 1) []
mv ssideki3.zip 'Sports' # Super Sidekicks 3 - The Next Glory / Tokuten Ou 3 - Eikou e no Michi []
mv ssrdrubc.zip 'Platform' # Sunset Riders (2 Players ver UBC) []
mv sstriker.zip 'Shooter' # Sorcer Striker []
mv stakwin2.zip 'Sports' # Stakes Winner 2 []
mv starcas.zip 'Shooter' # Star Castle (version 3) []
mv stargate.zip 'Shooter' # Stargate []
mv starglad.zip 'Vs Fighter' # Star Gladiator Episode I: Final Crusade (USA 960627) [Slow]
mv starswep.zip 'Puzzle' # Star Sweep (World, STP2/VER.A) []
mv starwars.zip 'Shooter' # Star Wars (set 1) []
mv stdragon.zip 'Shooter' # Saint Dragon (set 1) []
mv stmblade.zip 'Shooter' # Storm Blade (US) []
mv stoneba2.zip 'Sports' # Stone Ball (2 Players) []
mv strahl.zip 'Shooter' # Koutetsu Yousai Strahl (World) []
mv stratof.zip 'Shooter' # Raiga - Strato Fighter (US) []
mv strider.zip 'Platform' # Strider (USA, B-Board 89624B-2) []
mv strkforc.zip 'Shooter' # Strike Force (rev 1 02/25/91) []
mv superpac.zip 'Maze' # Super Pac-Man []
mv superspy.zip 'Fighter' # The Super Spy (NGM-011 ~ NGH-011) []
mv suprmrio.zip 'Platform' # Vs. Super Mario Bros. (set SM4-4 E) []
mv suratk.zip 'Platform' # Surprise Attack (World ver. K) []
mv svc.zip 'Vs Fighter' # SNK vs. Capcom - SVC Chaos (NGM-2690 ~ NGH-2690) []
mv swcourt.zip 'Sports' # Super World Court (World) []
mv tapper.zip 'Platform' # Tapper (Budweiser, 1/27/84) []
mv tbowl.zip 'Sports' # Tecmo Bowl (World, set 1) []
mv tbyahhoo.zip 'Shooter' # Twin Bee Yahhoo! (ver JAA) []
mv tcobra2.zip 'Shooter' # Twin Cobra II (Ver 2.1O 1995/11/30) []
mv teddybb.zip 'Platform' # TeddyBoy Blues (315-5115, New Ver.) []
mv tehkanwc.zip 'Sports' # Tehkan World Cup (set 1) []
mv tekken2.zip 'Vs Fighter' # Tekken 2 Ver.B (US, TES3/VER.D) [Slow]
mv tekken3.zip 'Vs Fighter' # Tekken 3 (World, TET2/VER.E1) [Slow]
mv tektagt.zip 'Vs Fighter' # Tekken Tag Tournament (World, TEG2/VER.C1, set 1) [Slow]
mv tengai.zip 'Shooter' # Tengai (World) []
mv terracre.zip 'Shooter' # Terra Cresta (YM3526 set 1) []
mv terraf.zip 'Shooter' # Terra Force []
mv tetrisp2.zip 'Puzzle' # Tetris Plus 2 (World, V2.8) []
mv thndrx2.zip 'Shooter' # Thunder Cross II (World) []
mv thndzone.zip 'Shooter' # Thunder Zone (World, Rev 1) []
mv thoop.zip 'Platform' # Thunder Hoop (Ver. 1, Checksum 02A09F7D) []
mv thunderx.zip 'Shooter' # Thunder Cross (set 1) []
mv tigeroad.zip 'Platform' # Tiger Road (US) []
mv timber.zip 'Platform' # Timber []
mv timeplt.zip 'Shooter' # Time Pilot []
mv timesold.zip 'Shooter' # Time Soldiers (US Rev 3) []
mv tmht2p.zip 'Fighter' # Teenage Mutant Hero Turtles (UK 2 Players, version U) []
mv tmnt22p.zip 'Fighter' # Teenage Mutant Ninja Turtles - Turtles in Time (2 Players ver UDA) []
mv tnzs.zip 'Platform' # The NewZealand Story (World, new version) (P0-043A PCB) []
mv toki.zip 'Platform' # Toki (World, set 1) []
mv tokkae.zip 'Puzzle' # Taisen Tokkae-dama (ver JAA) []
mv tophuntr.zip 'Platform' # Top Hunter - Roddy & Cathy (NGM-046) []
mv totcarn.zip 'Shooter' # Total Carnage (rev LA1 03/10/92) []
mv toypop.zip 'Maze' # Toypop []
mv tp84a.zip 'Shooter' # Time Pilot '84 (set 2) []
mv trackfld.zip 'Sports' # Track & Field []
mv triplep.zip 'Maze' # Triple Punch (set 1) []
mv trog.zip 'Maze' # Trog (rev LA5 3/29/91) []
mv trojan.zip 'Platform' # Trojan (US set 1) []
mv truxton.zip 'Shooter' # Truxton / Tatsujin []
mv truxton2.zip 'Shooter' # Truxton II / Tatsujin Oh []
mv ts2.zip 'Vs Fighter' # Battle Arena Toshinden 2 (Euro 951124) [Slow]
mv tumblep.zip 'Platform' # Tumble Pop (World) []
mv turfmast.zip 'Sports' # Neo Turf Masters / Big Tournament Golf []
mv turtles.zip 'Maze' # Turtles []
mv tutankhm.zip 'Maze' # Tutankham []
mv twincobr.zip 'Shooter' # Twin Cobra (World) []
mv twineag2.zip 'Shooter' # Twin Eagle II - The Rescue Mission []
mv twineagl.zip 'Shooter' # Twin Eagle - Revenge Joe's Brother []
mv twinhawk.zip 'Shooter' # Twin Hawk (World) []
mv twinspri.zip 'Shooter' # Twinkle Star Sprites []
mv uccops.zip 'Fighter' # Undercover Cops (World) []
mv ultennis.zip 'Sports' # Ultimate Tennis [Slow]
mv ultrax.zip 'Shooter' # Ultra X Weapons / Ultra Keibitai []
mv umk3.zip 'Vs Fighter' # Ultimate Mortal Kombat 3 (rev 1.2) []
mv unsquad.zip 'Shooter' # U.N. Squadron (USA) []
mv uopoko.zip 'Puzzle' # Puzzle Uo Poko (International) []
mv upndown.zip 'Maze' # Up'n Down (315-5030) []
mv vamphalf.zip 'Fighter' # Vamf x1/2 (Europe, version 1.1.0908) []
mv vanguard.zip 'Shooter' # Vanguard (SNK) []
mv varth.zip 'Shooter' # Varth: Operation Thunderstorm (World 920714) []
mv vasara.zip 'Shooter' # Vasara []
mv vasara2.zip 'Shooter' # Vasara 2 (set 1) []
mv vball.zip 'Sports' # U.S. Championship V'ball (US) []
mv vendet2p.zip 'Fighter' # Vendetta (World 2 Players ver. W) []
mv venture.zip 'Maze' # Venture (version 5 set 1) []
mv vf.zip 'Vs Fighter' # Virtua Fighter [Slow]
mv victroad.zip 'Shooter' # Victory Road []
mv viewpoin.zip 'Shooter' # Viewpoint []
mv vigilant.zip 'Platform' # Vigilante (World, Rev E) []
mv vimana.zip 'Shooter' # Vimana (World, set 1) []
mv viostorm.zip 'Fighter' # Violent Storm (ver EAC) []
mv viprp1.zip 'Shooter' # Viper Phase 1 (New Version, World) []
mv volfied.zip 'Puzzle' # Volfied (World, revision 1) []
mv vsav.zip 'Vs Fighter' # Vampire Savior: The Lord of Vampire (Euro 970519) []
mv wakuwak7.zip 'Vs Fighter' # Waku Waku 7 []
mv wardner.zip 'Platform' # Wardner (World) []
mv warriorb.zip 'Fighter' # Warrior Blade - Rastan Saga Episode III (Japan) []
mv waterski.zip 'Sports' # Water Ski []
mv watrball.zip 'Puzzle' # Water Balls []
mv wb3.zip 'Platform' # Wonder Boy III - Monster Lair (set 6, World, System 16B) (8751 317-0098) []
mv wbml.zip 'Platform' # Wonder Boy in Monster Land (Japan New Ver., MC-8123, 317-0043) []
mv wboy.zip 'Platform' # Wonder Boy (set 1, 315-5177) []
mv wc90.zip 'Sports' # Tecmo World Cup '90 (World) []
mv welltris.zip 'Puzzle' # Welltris (World?, 2 players) []
mv wg3dh.zip 'Sports' # Wayne Gretzky's 3D Hockey (ver 1.3) [Slow]
mv whp.zip 'Vs Fighter' # World Heroes Perfect []
mv willow.zip 'Platform' # Willow (World) []
mv winspike.zip 'Sports' # Winning Spike (ver EAA) []
mv wiz.zip 'Platform' # Wiz []
mv wizdfire.zip 'Fighter' # Wizard Fire (Over Sea v2.1) []
mv wjammers.zip 'Sports' # Windjammers / Flying Power Disc []
mv wndrplnt.zip 'Shooter' # Wonder Planet (Japan) []
mv wof.zip 'Fighter' # Warriors of Fate (World 921031) []
mv wow.zip 'Maze' # Wizard of Wor []
mv wwfmania.zip 'Sports' # WWF: Wrestlemania (rev 1.30 08/10/95) []
mv wwfwfest.zip 'Sports' # WWF WrestleFest (World) []
mv xevi3dg.zip 'Shooter' # Xevious 3D/G (World, XV32/VER.B) [Slow]
mv xevious.zip 'Shooter' # Xevious (Namco) []
mv xexex.zip 'Shooter' # Xexex (ver EAA) []
mv xexexj.zip 'Shooter' # Xexex (ver JAA) []
mv xmcota.zip 'Vs Fighter' # X-Men: Children of the Atom (Euro 950331) []
mv xmen2p.zip 'Fighter' # X-Men (2 Players ver AAA) []
mv xmultipl.zip 'Shooter' # X Multiply (World, M81 hardware) []
mv xmvsfu.zip 'Vs Fighter' # X-Men Vs. Street Fighter (USA 961023) []
mv xsleena.zip 'Platform' # Xain'd Sleena (World) []
mv xybots.zip 'Maze' # Xybots (rev 2) []
mv zaxxon.zip 'Shooter' # Zaxxon (set 1, rev D) []
mv zerowing.zip 'Shooter' # Zero Wing (2P set) []
mv zookeep.zip 'Platform' # Zoo Keeper (set 1) []